from map import MAPPING

WIDTH = 800
HEIGHT = 800

VISIBLE_WIDTH = 500
VISIBLE_HEIGHT = 500

CELL_SIZE = MAPPING['1']['size']
HALF_CELL_SIZE = CELL_SIZE / 2

X_CELLS = int(WIDTH / CELL_SIZE)
Y_CELLS = int(HEIGHT / CELL_SIZE)

DIAGONAL_DIRECTIONS = (('UP', 'RIGHT'), ('UP', 'LEFT'), ('DOWN', 'RIGHT'), ('DOWN', 'LEFT'))

MOVEMENT_KEYS = dict(
    UP=['w', 87, 38],
    DOWN=['s', 83, 40],
    LEFT=['a', 65, 37],
    RIGHT=['d', 68, 39]
)
